name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  SERVICE_NAME: movie-catalog-service  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      env:
        COMMIT_HASH: ${{ github.sha }}
        DOCKER_REPO_OWNER: utsabroy
      run: |
        docker build . --file Dockerfile --tag ${SERVICE_NAME}:${COMMIT_HASH:0:7}
        docker tag ${SERVICE_NAME}:${COMMIT_HASH:0:7} ${DOCKER_REPO_OWNER}/${SERVICE_NAME}:${COMMIT_HASH:0:7}
        docker push ${DOCKER_REPO_OWNER}/${SERVICE_NAME}:${COMMIT_HASH:0:7}
